name: Run Dhan Auto Trade

on:
  schedule:
    - cron: "28 15 * * 5"   # Every Friday 3:28 PM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set Timezone to IST
      run: sudo timedatectl set-timezone Asia/Kolkata

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Run Auto Trading Script
      run: python dhan.py
